### ISSUE TITLE
第 5 章的 typo 与格式问题

### ISSUE THREAD

**Issue by RustingSword** [nndl/textbook-comments#4]
https://nndl.github.io/ch5.pdf 版本 1/18  1:45

所引页码是页眉"#"之后的数字。

1. p1 5.1下面，“学习算法”之后应该换行？
2. p2 第一行，“生物神经元有一个阀值……”，这里的两处“阀值”应为“阈值”。
3. p3 数学小知识中，“若x->-∞是”“若x->+∞是”，“是”应为“时”。
4. p9 倒数第二段，“并不是否合理”，“是否”应为“十分”？“而不是有多层的感知器”应为“而不是由多层的感知器”。
5. p11 第一段，"f(x;W,b))"，多余的右括号；5.2.2，“要取好的分类效果”，脱漏“得”字。
6. p14 中间，“然后，在乘上”，应为“然后，再乘上”。
7. p16 第一段最后一行，“无序”应为“无须”。
8. p19 倒数第三段，“前面模式”应为“前向模式”；倒数第三行，“自动微分在无需”应为“自动微分则无需”。
9. p21 “每次迭代（随机）（选择一个样本计算梯度”，括号是多余的。
10. p28 5.7.5 引文缺失。
11. p29 中间，“随机森林？”疑似衍文？

**Comment by xpqiu** [comment]
多谢，可否告诉我你的名字，我在书中致谢下：）

**Comment by RustingSword** [comment]
邱老师太客气了，举手之劳，不足挂齿：）
