### ISSUE TITLE
ch5 typos

### ISSUE THREAD

**Issue by endyul** [nndl/textbook-comments#5]
p#4, Eq(5.7), missing `x`, should be `g_{l}\left ( x \right )\approx \sigma\left( 0 \right) + {\sigma}'\left( 0 \right) x`

p#4, Eq(5.12), missing `x`, should be `g_{t}\left ( x \right )\approx tanh\left( 0 \right) + {tanh}'\left( 0 \right) x`

p#7, Maxout: 可以得到k个净输入z -> 可以得到k个净输出z

**Comment by xpqiu** [comment]
已修正，多谢！
