### ISSUE TITLE
第五章typo

### ISSUE THREAD

**Issue by intfloat** [nndl/textbook-comments#6]
Page 79, 记忆网络部分，“和反馈网络相比, **反馈网络**具有更强的记忆功能” 应为 “和反馈网络相比,**记忆网络**具有更强的记忆功能”

Page 85, Eq 5.57 上面 “关于第 l 层偏置 **W^(l)** 的梯度” 应为 “关于第 l 层偏置 **b^ (l)** 的梯度”

Page 86, 算法 5.1 “用公式5.56和5.57每一层参数的导数”， 疑似漏掉了 “计算” 两个字，应为 “用公式5.56和5.57**计算**每一层参数的导数”

Page 89, Eq 5.79下面那一段， 第一句话 “两种梯度累积**损失**” 感觉应为 “两种梯度累积**方式**”

Page 95, Eq 5.89 上面那一段 “减弱**的**神经网络的非线性性质” 应为 “减弱**了**神经网络的非线性性质”

Page 99, 最后一段，“其可以**被**是给数据增加噪声”， 应去掉多余的“被”字。

**Comment by xpqiu** [comment]
谢谢反馈！
